### ISSUE TITLE
分类里怎么添加不同的头部壁纸？

### ISSUE THREAD

**Issue by leokaka1** [JaydenForYou/CREAMy#1]
typeCho中只有独立页面可以添加头部壁纸，但是分类你不行，如何能像你的博客一样把分类也添加不同的头部壁纸？

**Comment by JaydenForYou** [comment]
这个功能，我没有写，有时间 我加上。

**Comment by unsafe-ptr** [comment]
> typeCho中只有独立页面可以添加头部壁纸，但是分类你不行，如何能像你的博客一样把分类也添加不同的头部壁纸？

这个功能，我没有写，有时间 我加上。

**Comment by unsafe-ptr** [comment]
> typeCho中只有独立页面可以添加头部壁纸，但是分类你不行，如何能像你的博客一样把分类也添加不同的头部壁纸？

看下文档，已经更新了。
