### ISSUE TITLE
无法保存设置

### ISSUE THREAD

**Issue by wx0716** [JaydenForYou/CREAMy#2]
# 写完设置点击保存设置，然后所有的设置都被清空了，是怎么回事？

**Comment by JaydenForYou** [comment]
可以正常保存，另外TYPECHO主题间切换会丢失上一个主题的设置

**Comment by unsafe-ptr** [comment]
> # 写完设置点击保存设置，然后所有的设置都被清空了，是怎么回事？

可以正常保存，另外TYPECHO主题间切换会丢失上一个主题的设置
