### ISSUE TITLE
文章的格式有误

### ISSUE THREAD

**Issue by jasperleung97** [JaydenForYou/CREAMy#3]
里面的h1, h2, h3那些全部都不起作用了。

**Comment by unsafe-ptr** [comment]
> 里面的h1, h2, h3那些全部都不起作用了。

使用markdown

**Comment by diyhome** [comment]
markdown格式也有错误,请参考:https://blog.banjinl.icu/index.php/about.html
貌似是渲染的问题,目前服务器环境是lnmp
php版本:7.3
